<a href="https://colab.research.google.com/github/emreKanarya/-Zekasi-ve-Veri-Madenciligi/blob/main/HAFTA_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Basit bir dizi oluşturalım.

In [ ]:
a=np.array([1,2,3])
print(a)

[1 2 3]


3 tane sıfırlardan oluşan dizi oluşturalım.

In [ ]:
b=np.zeros(3)
print(b)

[0. 0. 0.]


3 tane sıfırlardan oluşan dizi oluşturalım.

In [ ]:
x=np.ones(4)
print(x)

[1. 1. 1. 1.]


Rastgele sayılardan oluşan dizi oluşturalım.Ürettiği her elemanı 10 ile çarpalım.

In [ ]:
y=np.random.random(10)
print(y*10)

[3.26117143 0.6049082  9.08372711 6.06081609 3.04206044 8.07433255
 7.10668835 7.20010114 3.37708158 7.41488797]


2 boyutlu, çok boyutlu dizi oluşturalım.

In [ ]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(y)

[0.32611714 0.06049082 0.90837271 0.60608161 0.30420604 0.80743326
 0.71066883 0.72001011 0.33770816 0.7414888 ]


Ben yukarıdaki 2 numaralı değere ulaşmak istiyorum. Yani 0.060 ile başlayan değere.

In [ ]:
print(y[1])

0.06049082014163254


Peki ilk değerden ikinci değere kadar olan değerler yani ilk ikisi 0:2 demem lazım çünkü 2 dahil olmaz 1 i alır böylelikle numpyda böyle yani. Şöylede yapılabilir"([:2])" aynı sonucu elde ederiz. 

In [ ]:
print(y[0:2])

[0.32611714 0.06049082]


In [ ]:
print(y[1:])

[0.06049082 0.90837271 0.60608161 0.30420604 0.80743326 0.71066883
 0.72001011 0.33770816 0.7414888 ]


In [ ]:
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Ben yukarıdaki 3 e ulaşmak istiyorum ne yapmalıyım.

In [ ]:
print(c[1,1])

5


Aşağıda 1. satırı al dedik daha sonra sütunda en baştan başla 1 e kadar al dedik fakat numpy da 1 dahil olmadı, 1 e kadar olan kısmı aldı.

In [ ]:
print(c[1,:1])

[4]


In [ ]:
print(c[:,2])

[3 6 9]


5 satır 3 sütundan oluşan bir matris yazalım.

In [ ]:
d=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


"shape" fonksiyonu bize kaça kaçlık bir matris olduğunu veriyor.

In [ ]:
print(d.shape)

(5, 3)


"reshape" fonksiyonu matrisimizin boyutunu yeniden düzenlememizi sağlıyor. Örneğin bizim d miz 5 satır 3 sütundan oluşuyor fakat biz bunu reshape ile 3 satır 5 sütundan oluşturalım.

In [ ]:
print(d.reshape(3,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [ ]:
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Ben yukaridaki dizeden 7,8,9 u elde etmek istiyorum ne yapmalıyım?

In [ ]:
print(c[2,:])

[7 8 9]


In [ ]:
print(d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


Yukarıdan 12 i ve 15 i elde etmek istiyorum.

In [ ]:
print(d[3:,2])

[12 15]


11,12,14,15 i elde etmek istiyorum ne yapmalıyım?

In [ ]:
print(d[3:,1:])

[[11 12]
 [14 15]]


4 ve 5 i elde etmek istiyorum.

In [ ]:
print(d[1:2,0:2])

[[4 5]]


8,9,11,12 yi elde etmek istiyoruz.

In [ ]:
print(d[2:4,1:])

[[ 8  9]
 [11 12]]


".ndim" bize dizinin boyutunu verir.

In [ ]:
print(c.ndim)

2


In [ ]:
print(a)

[1 2 3]


"arange" fonksiyonu bize belirlediğimiz sayılar arasında kaçar ilerleyeceğini belirttiğimiz fonksiyonu sağlar.
Örneğin 1 DEN 9 A KADAR 5 ER ARTARAK İLERLESİN İSTEDİĞİMİZ BİR DİZİ OLUŞTURALIM. 

In [ ]:
e=np.arange(1,9,5)
print(e)

[1 6]


Örnek: 1 İLE 100 ARASINDA 7 YE BÖLÜNEBİLEN SAYILARDAN OLUŞAN BİR DİZİ OLUŞTURUNUZ.

In [ ]:
o=np.arange(0,101,7)
print(o[1:])

[ 7 14 21 28 35 42 49 56 63 70 77 84 91 98]


"linspace" fonksiyonu başlangıç noktası bitiş noktası dahil kaç tane eşit aralıklı sayı oluşturacaksanız onu ifade ediyorsunuz. ÖRNEĞİN 0 DAHİL OLACAK 10 DAHİL OLACAK TOPLAMDA 7 TANE ARDIŞIK DEĞERLERDEN OLUŞAN BİR DİZİ OLUŞTURALIM. 

In [ ]:
v=np.linspace(0,10,7)
print(v)

[ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.        ]


Örnek: 20 ile 21 arasında eşit aralıklı 20 tane değer üretiniz.

In [ ]:
p=np.linspace(20,21,20)
print(p)

[20.         20.05263158 20.10526316 20.15789474 20.21052632 20.26315789
 20.31578947 20.36842105 20.42105263 20.47368421 20.52631579 20.57894737
 20.63157895 20.68421053 20.73684211 20.78947368 20.84210526 20.89473684
 20.94736842 21.        ]


Örnek: d1 ve d2 adında iki dizi oluşturun 3x3 lük olsunlar. Random,arange reshapelinspace kullanabilirsiniz.

In [ ]:
d1=np.random.random(9)
d2=np.random.random(9)
print(d1.reshape(3,3))

[[0.16335928 0.15469979 0.32763149]
 [0.83990779 0.75817079 0.51375033]
 [0.58647586 0.538827   0.46055862]]


Yukarıdaki çıkan sonuçların tam sayı olması için "arange" fonksiyonunu kullanarak yapalım.

In [ ]:
d1=np.arange(10,28,2)
d2=np.arange(30,48,2)
d1a=d1.reshape(3,3)
d2a=d2.reshape(3,3)
print(d1a)

[[10 12 14]
 [16 18 20]
 [22 24 26]]


Peki yukarıdaki iki diziyi birleştirmek istiyorum nasıl birleştirebilirim? Yani yukarıdaki d1a ve d2a yı. Hem yatay eksende hem de dikey eksende birleştirme yapalım "concatenate" fonksiyonu yardımı ile.

In [ ]:
d1=np.arange(10,28,2)
d2=np.arange(30,48,2)
d1a=d1.reshape(3,3)
d2a=d2.reshape(3,3)
yatay=np.concatenate([d1a,d2a],axis=0)
dikey=np.concatenate([d1a,d2a],axis=1)
print(dikey)

[[10 12 14 30 32 34]
 [16 18 20 36 38 40]
 [22 24 26 42 44 46]]


Dikey dizisi içerisindeki EN BÜYÜK DEĞERİ nasıl bulabiliriz?

In [ ]:
print(dikey.max())

46


Dikey dizisi içerisindeki EN KÜÇÜK DEĞERİ nasıl bulabiliriz?

In [ ]:
print(dikey.min())

10


Dikey dizisi içerisindeki TÜM DEĞERLERİN TOPLAMINI nasıl bulabiliriz?

In [ ]:
print(dikey.sum())

504


Dikey dizisi içerisindeki TÜM DEĞERLERİN ORTALAMASINI nasıl bulabiliriz?

In [ ]:
print(dikey.mean())

28.0


Dikey dizisi içerisindeki değeri 50 den büyük olan var mı?

In [ ]:
d1=np.arange(10,28,2)
d2=np.arange(30,48,2)
d1a=d1.reshape(3,3)
d2a=d2.reshape(3,3)
yatay=np.concatenate([d1a,d2a],axis=0)
dikey=np.concatenate([d1a,d2a],axis=1)
print(dikey>50)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]]


PANDAS a GİRİŞ YAPIYORUZ.PANDAS "DATAFRAEM" ler ÜZERİNDE İŞLEM YAPMAMIZI SAĞLIYOR.

In [ ]:
import pandas as pd


In [ ]:
x=np.arange(1,20,2)
print(x)

[ 1  3  5  7  9 11 13 15 17 19]


Numpy ı datafraem e dönüştürelim.Bunun için öncelikle datafraem nesnesi oluşturuyoruz.

In [ ]:
y=np.arange(1,12,2).reshape(2,3)
df=pd.DataFrame(y,columns=["Ali","Ayşe","Mehmet"])
df

Ali  Ayşe  Mehmet
0    1     3       5
1    7     9      11