# Neden NumPy?

In [5]:
a=[1,2,3,4]
b=[2,3,4,5]

In [9]:
ab=[]

for i in range(0, len(a)):
    ab.append(a[i]*b[i])
    
ab    

[2, 6, 12, 20]

In [10]:
import numpy as np

In [11]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])

In [12]:
a*b

array([ 2,  6, 12, 20])

In [15]:
a=np.array([1,2,3,4,5])  #Array oluşturma

In [16]:
a

array([1, 2, 3, 4, 5])

In [17]:
type(a)

numpy.ndarray

In [20]:
np.array([3.14, 4, 2, 13], dtype = "float32") # Veri tipini bu şekilde değiştirebiliriz.

array([ 3.14,  4.  ,  2.  , 13.  ], dtype=float32)

In [23]:
np.zeros(10)#, dtype = int)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [27]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [30]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [31]:
np.random.normal(10,4,(3,4)) #Ortalaması 4, Standart sapması 4 olacak şekilde 3 e 4 lük bir matris oluşturduk.

array([[12.82008012,  2.22653452, 13.09369576, 14.8017891 ],
       [15.13074744,  9.3693846 , 14.36189724, 11.28990489],
       [ 6.73177325,  7.87407683,  5.82865173,  9.00668185]])

In [32]:
np.random.randint(0,10,(3,3))

array([[7, 5, 6],
       [0, 4, 8],
       [2, 6, 8]])

In [33]:
import numpy as np

In [34]:
np.random.randint(10, size=10)

array([8, 4, 8, 3, 2, 9, 0, 8, 4, 9])

In [36]:
a.ndim #Dizinin boyutunu bize verir.

1

In [38]:
a=np.random.randint(10, size=10)

In [39]:
a

array([0, 3, 4, 5, 9, 3, 8, 4, 9, 6])

In [40]:
a.shape #Tek boyutlu olduğu için sadece 10 verdi. 10 tane eleman var dedi.

(10,)

In [41]:
a.size #Toplam eleman sayısını bize verir.

10

In [42]:
a.dtype #Veri türünü bize verir.

dtype('int32')

In [44]:
# İki boyutlu array oluşturalım.

b= np.random.randint(10, size=(3,5))

In [45]:
b

array([[4, 7, 2, 4, 3],
       [0, 6, 2, 1, 1],
       [3, 5, 4, 3, 7]])

In [46]:
b.ndim

2

In [47]:
b.shape

(3, 5)

In [48]:
b.size

15

In [49]:
b.dtype

dtype('int32')

In [50]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
# Yukarıdaki tek boyutlu array imizi 2 boyutlu hale getirelim reshape ile.

a=np.arange(1,10).reshape((3,3))

In [53]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
a.shape

(3, 3)

In [55]:
a.ndim

2

In [56]:
a= np.arange(1,10)

In [57]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
a.ndim

1

In [60]:
#önemli: Tek boyutlu array VEKTÖR dür.
#İki boyutlyu array ise MATRİS dir.

In [61]:
b=a.reshape((1,9))

In [62]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [63]:
b.ndim

2

In [64]:
a.ndim

1

In [65]:
#ARRAY BİRLEŞTİRME İŞLEMİ

In [66]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [67]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [69]:
z=np.array([7,8,9]) # listeyi de ekleyebilir miyiz bakalım.

In [71]:
r=np.concatenate([x,y,z])

In [72]:
r

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
r.ndim

1

In [74]:
# İki Boyut Yapalım.

In [80]:
a=np.array([[1,2,3],
            [4,5,6]])

In [81]:
l=np.concatenate([a,a])

In [82]:
l

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [83]:
l.ndim

2

In [84]:
# Satır değilde sütun olarak birleştirmek istiyorum.

In [87]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [88]:
#ARRAY AYIRMA İŞLEMİ

In [90]:
x=np.array([1,2,3,99,99,3,2,1]) #Ben bunları 3 parçaya ayırmak istiyorum.

In [94]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [95]:
a,b,c = np.split(x, [3,5]) # Bçlünenleri 3 par.aya böldük a, b, c olarak.

In [96]:
a

array([1, 2, 3])

In [97]:
b

array([99, 99])

In [98]:
c

array([3, 2, 1])

In [99]:
# İKİ BOYUTLU AYIRMA İŞLEMLERİ

In [100]:
m= np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [101]:
#Biz şimdi ikinci satırsan sonraki kısmı silip dikey olarak yana eklemek istiyoruz.

In [103]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [104]:
ust, alt = np.vsplit(m, [2])

In [105]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [106]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [107]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [108]:
sag, sol = np.hsplit(m, [2])

In [109]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [110]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [111]:
# SIRALAMA İŞLEMLERİ

In [113]:
v=np.array([2,1,4,3,5])

In [114]:
v

array([2, 1, 4, 3, 5])

In [115]:
np.sort(v) # Bu fonksiyon ile kücükten büyüge doğru sıralandı.

array([1, 2, 3, 4, 5])

In [116]:
v.sort() # np içinden .ağırmadığımız icin yapısını bozdu.

In [117]:
v

array([1, 2, 3, 4, 5])

In [118]:
# İKİ BOYUTLU ARRAY SIRALAMA.

In [121]:
m= np.random.normal(20,5, (3,3))

In [122]:
m

array([[14.98315725, 22.77411986, 29.61653908],
       [24.08063746, 21.87948964, 19.89794825],
       [22.2346439 , 29.88186219, 10.80109653]])

In [123]:
# Buradaki iki boyutlu arrayin satırlarını sıralayalım.

In [124]:
np.sort(m, axis = 1) # Bu şekilde satırları büyükten kücüge sıraladı.

array([[14.98315725, 22.77411986, 29.61653908],
       [19.89794825, 21.87948964, 24.08063746],
       [10.80109653, 22.2346439 , 29.88186219]])

In [128]:
np.sort(m, axis = 0) # Bu şekiklde sütunları sıraladı.

array([[14.98315725, 21.87948964, 10.80109653],
       [22.2346439 , 22.77411986, 19.89794825],
       [24.08063746, 29.88186219, 29.61653908]])

In [129]:
# Index ile Elemanlara Erişmek.

In [130]:
a = np.random.randint(10, size=10)
a

array([3, 8, 3, 2, 7, 7, 6, 5, 9, 5])

In [131]:
a[0]

3

In [132]:
a[-1]

5

In [133]:
a[0]=100 # 0 ıncı indexte bulunan değerin numarası "100" oldu artık.

In [134]:
a

array([100,   8,   3,   2,   7,   7,   6,   5,   9,   5])

In [135]:
# İki Boyutlu matristen bunu yapalım index ile erişme işlemini

In [136]:
m = np.random.randint(10, size=(3,5))
m

array([[9, 9, 0, 9, 3],
       [5, 6, 9, 3, 5],
       [4, 5, 9, 4, 6]])

In [137]:
m[0,0]

9

In [138]:
m[0,1]

9

In [141]:
m[1,4]

5

In [142]:
m[1,4]=99

In [143]:
m

array([[ 9,  9,  0,  9,  3],
       [ 5,  6,  9,  3, 99],
       [ 4,  5,  9,  4,  6]])

In [144]:
m[1,4]=2.2

In [145]:
m

array([[9, 9, 0, 9, 3],
       [5, 6, 9, 3, 2],
       [4, 5, 9, 4, 6]])

In [146]:
a=np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [147]:
a[0:3]

array([20, 21, 22])

In [148]:
a[:3]

array([20, 21, 22])

In [149]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [150]:
a[1::2]

array([21, 23, 25, 27, 29])

In [151]:
a[0::2]

array([20, 22, 24, 26, 28])

In [152]:
a[0::3]

array([20, 23, 26, 29])

In [153]:
 # İKİ BOYUTLU SLICE İŞLEMLERİ

In [157]:
m=np.random.randint(10, size= (5,5))

In [158]:
m

array([[2, 1, 9, 6, 7],
       [4, 5, 4, 7, 3],
       [3, 7, 4, 4, 7],
       [7, 9, 7, 0, 0],
       [6, 3, 1, 9, 1]])

In [168]:
kuııo

array([[4, 5, 4, 7, 3],
       [3, 7, 4, 4, 7]])

In [160]:
m[:]

array([[2, 1, 9, 6, 7],
       [4, 5, 4, 7, 3],
       [3, 7, 4, 4, 7],
       [7, 9, 7, 0, 0],
       [6, 3, 1, 9, 1]])

In [171]:
m[2,:]

array([3, 7, 4, 4, 7])

In [172]:
m[0:2, 0:3]

array([[2, 1, 9],
       [4, 5, 4]])

In [173]:
m[::,:2] #tÜM SATRIRLAR ALINDI VE İLK VE İKİNCİ SÜTUNU ALDI 2 DAHİL DEĞİL.

array([[2, 1],
       [4, 5],
       [3, 7],
       [7, 9],
       [6, 3]])

In [174]:
m[1:3, 0:2]

array([[4, 5],
       [3, 7]])

In [177]:
a = np.random.randint(30, size=(5,5))
a

array([[17, 16,  1,  3, 27],
       [17, 24, 29, 29, 14],
       [15, 29, 21,  2, 28],
       [10, 26, 20, 20, 23],
       [13, 21, 14, 22,  7]])

In [180]:
alt_a=a[0:3, 0:2]
alt_a

array([[17, 16],
       [17, 24],
       [15, 29]])

In [181]:
alt_a[0,0]=9999
alt_a[1,1]=8888

In [183]:
alt_a

array([[9999,   16],
       [  17, 8888],
       [  15,   29]])

In [184]:
a

array([[9999,   16,    1,    3,   27],
       [  17, 8888,   29,   29,   14],
       [  15,   29,   21,    2,   28],
       [  10,   26,   20,   20,   23],
       [  13,   21,   14,   22,    7]])

In [186]:
m = np.random.randint(30, size=(5,5))
m

array([[ 2, 22, 15, 15, 16],
       [ 9, 16, 21, 19, 14],
       [15,  9, 23, 25, 25],
       [11, 21, 21, 13, 27],
       [10, 21,  5, 13, 25]])

In [187]:
alt_b=m[0:3, 0:2].copy() #Ana veride hata değşiklik olmaması için COPY metodunu klullandık.
alt_b

array([[ 2, 22],
       [ 9, 16],
       [15,  9]])

In [188]:
alt_b[0,0]=9999
alt_b[1,1]=8888

In [192]:
alt_b*3

array([[29997,    66],
       [   27, 26664],
       [   45,    27]])

In [191]:
m

array([[ 2, 22, 15, 15, 16],
       [ 9, 16, 21, 19, 14],
       [15,  9, 23, 25, 25],
       [11, 21, 21, 13, 27],
       [10, 21,  5, 13, 25]])

In [193]:
#FANCY INDEX ÇOK ÖNEMLİ BU KISIMA GEÇTİK ŞİMDİ

In [194]:
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [197]:
v[1]

3

In [198]:
v[3]

9

In [199]:
v[5]

15

In [200]:
#Bunların üçünü bir arada görelim.
[v[1], v[3], v[5]]

[3, 9, 15]

In [201]:
al_getir=[1,3,5]

In [202]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [203]:
v[al_getir] #işte burada FANCY INDEX i kullandık.

array([ 3,  9, 15])

In [205]:
git_gotur=[2,4,6]

In [206]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [207]:
v[git_gotur]

array([ 6, 12, 18])

In [208]:
#İKİ BOYUTTA FANCY

In [214]:
m=np.arange(12).reshape((4,3))

In [215]:
m

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [216]:
#Koşullu Eleman İşlemleri

In [217]:
v=np.array([1,2,3,4,5])

In [220]:
v<3

array([ True,  True, False, False, False])

In [221]:
v[v<3]

array([1, 2])

In [222]:
v[v!=3]

array([1, 2, 4, 5])

In [223]:
v-1

array([0, 1, 2, 3, 4])

In [224]:
#UFUNC İŞLEMLERİ ÖNEMLİ

In [227]:
# NUMPY İLE 2 BİLİNMEYENLİ DENKLEM ÇÖZÜMÜ

5*X0+X1=12

X0+3*X1=10

In [230]:
a=np.array([[5,1], [1,3]])
b=np.array([12,10])

In [231]:
a

array([[5, 1],
       [1, 3]])

In [232]:
b

array([12, 10])

In [233]:
x=np.linalg.solve(a,b)

In [234]:
x

array([1.85714286, 2.71428571])

ÖRNEK SORULAR VE ÇÖZÜMLERİ

In [236]:
a=np.array([3.14, 4, 6, 1.2])
a

array([3.14, 4.  , 6.  , 1.2 ])

In [237]:
a=np.ones((2,3))

In [238]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [239]:
a.shape

(2, 3)

In [240]:
a.ndim

2

In [241]:
a.size

6

In [242]:
a.dtype

dtype('float64')

In [268]:
np.random.randint(10, size=(3,2,5))

array([[[0, 1, 2, 0, 8],
        [4, 6, 8, 4, 8]],

       [[3, 7, 1, 4, 9],
        [7, 6, 4, 4, 5]],

       [[0, 0, 0, 9, 1],
        [7, 2, 9, 1, 7]]])

In [271]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [275]:
x=np.array([1,2,3])
y=np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [276]:
5*np.array([1,2,3])

array([ 5, 10, 15])

In [277]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [278]:
v=np.array([2,1,4,3,5])
np.sort(v)

array([1, 2, 3, 4, 5])

In [279]:
v[2]

4

In [283]:
v=([7,3,4,7,0,9,3,2,9,2])

In [284]:
v[-2]

9

In [286]:
a.ndim

2

In [292]:
a=np.array([[4, 7, 4, 5, 9],
[2, 5, 0, 7, 7],
[1, 9, 0, 8, 2]])
a

array([[4, 7, 4, 5, 9],
       [2, 5, 0, 7, 7],
       [1, 9, 0, 8, 2]])

In [291]:
a[:,2]

array([4, 0, 0])

In [293]:
s=np.array([ 0, 3, 6, 9, 12, 15, 18, 21, 24, 27])

In [294]:
[v[1],v[3]]

[3, 7]

In [295]:
v = np.array([ 0, 3, 6, 9, 12, 15, 18, 21, 24, 27])

In [297]:
v[[1,2,3]] #Fancy Index Islemi yapıldı.

array([3, 6, 9])